### ISSUE TITLE
Sony ARW files don't report any locations

### ISSUE THREAD

**Issue by pbranly** [nemethviktor/GeoTagNinja#10]
Hi
I have a lot of Sony photos in ARW format that are position tagged
But geotagninja does not report any location
See snaps
![2022-10-23_18-37](https://user-images.githubusercontent.com/22018509/197404419-fa07f6c8-9d97-435e-a34f-8b24aa3ee449.png)

Philippe
![2022-10-23_18-36](https://user-images.githubusercontent.com/22018509/197404422-a8483bde-45a8-4a4a-aff1-cdf09adcd2e2.png)

**Comment by nemethviktor** [comment]
Hey, thanks for that, could you please upload any sample to Google drive or a public place I can download and test?

**Comment by pbranly** [comment]
https://www.dropbox.com/sh/4k4ak701h1i4sjm/AAC5QrKNVD--xq09BLBfj5MYa?dl=0
please find some samples
those photos were taken in Roma with a Sony RX10. 
Positions were added with geosetter software from a file coming from an apple applett called pixtrack
For each photo you will find the "original" one without position (just rename to .arw) in case of use

Please confirm when I can remove those photos from my dropbox directory
Phil

**Comment by nemethviktor** [comment]
Thanks, the photos can be removed from dropbox - I'll have a look at the issue shortly

**Comment by nemethviktor** [comment]
Hmm, interesting. So on my (UK English Win11) it looks okay actually...in GTN but not "in Windows":
![image](https://user-images.githubusercontent.com/58767235/197497411-c60d7520-593b-473c-98af-cdec6d7e1659.png)

(that's the 
I'll fire up a French Windows and see if it's the same.

**Comment by pbranly** [comment]
interesting !
What do you mean with "GTN" ?
By the way any help you would need will be okay on my side
Phil

**Comment by nemethviktor** [comment]
GTN = geotagninja :)
Haven't yet looked at the French Windows but just checking if you're FRE France or Canada (it's a different internal setting, that might affect stuff, not sure at this point) and you're Windows 10 or 11 pls?

**Comment by nemethviktor** [comment]
Okay it works ok on Win10 FRE France
![image](https://user-images.githubusercontent.com/58767235/197512817-86e1069b-8bf2-404a-ae7f-3364c5c7d209.png)

Not sure yet where the issue is but we'll figure it out :)

**Comment by nemethviktor** [comment]
I'm just installing W11 Home FRE...
In the meanwhile, what's the path (full path) to your pictures? What happens if you move the files to something like C:\temp? (no spaces, no special characters, no umlauts)
"Compatibility mode" shouldn't really be an issue. I think for some reason exiftool isn't reading the tags in the files in your case, or it's reading something that's misaligned.

**Comment by pbranly** [comment]
Hi
Well done !
the full path is :D:\Photos à developper\taguées\Sony (that means with blanks, accents , etc !)
under d:/test it works 

I changes the path to D:\Photos_a_developper\taguees and it works

then I changed to D:\Photos a developper\taguees and it works as well. 
This means that it does not support the accents 
this could be added in the documentation 
Phil


fine ! good to know

**Comment by nemethviktor** [comment]
Yayyy. 
You can try:

> How to enable UTF-8:
> 
> Control Panel > Clock and Region > Region > Administrative tab > Change system locale button > enable Beta:Use Unicode UTF-8 for worldwide language support.
> 
> The same GUI window can also be launched from Settings > Time & Language > Language & region > Administrative language settings > Administrative tab > Change system locale button > enable Beta:Use Unicode UTF-8 for worldwide language support.

(You'll then need to restart) -- See if it works afterwards. Worst case, yes, you may need to store the files in a "shorter" folder...
Spaces should be okay I think but there's some thing about unicode characters taking up too much byte-space (ie I think exiftool can only do 260 chars of path length but this is further limited by the individual byte-space each char takes up and for some UTF characters that's 2-4 bytes.)

**Comment by pbranly** [comment]
work around : for french characters dont use accents in the path
