### ISSUE TITLE
Bulk GPS editing, each photo has its own GPS coordinates

### ISSUE THREAD

**Issue by NO-MAN-CAT** [nemethviktor/GeoTagNinja#100]
**Is your feature request related to a problem? Please describe.**
I recorded the GPS coordinates in a KML/GPX file using a phone app.
I am tagging GPS coordinates to photos in bulk - each photo has its own GPS coordinates and I have to click a lot.

**Describe the solution you'd like**

- In the "Edit Data" pop-up window, I would like to click on the "Ok and Next photo". Please see _Screenshot №1_

- In the "Edit data" pop-up window, I would like to paste a coordinates in one field as _78.219118, 15.654376_. Please see _Screenshots №2 and №3_

**Additional context**
Screenshot №1
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/dbe542b9-00d3-47ac-8335-57a86719a04e)

Screenshot №2
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/4f755648-62c0-4aee-a9ac-ff5206f5ce18)

Screenshot №3
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/de8a28f5-08a2-411a-abad-c1c51192a144)

Imagine an amount of clicks that a user should do to bulk edit a 100 photos.. If anything, I'm not complaining, just thought that these features would be useful for some users
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/b0ace28e-296d-46cc-a639-4513584d3d66)

**Comment by nemethviktor** [comment]
Can you have a test drive of https://drive.google.com/open?id=16laoPJcsJJz6mdkcjWvoQu6wWXiILbQy&usp=drive_fs pls -- that in particular to the two features you asked for (move to next button and paste).
thnx

**Comment by NO-MAN-CAT** [comment]
> Why don't you use the Import GPX function? (File Menu) I can add the things you asked for but apart from that the above function is for bulk sync and import of GPX stuff.


Sometimes, but not in this case, I tag photos using just Google Maps and its feature to right-click and copy coordinates.

In this case, I tried using the GPX import function, but it works a little differently than I expected. In my case, I have 90 photos and 90 GPX waypoints (manual markers). When I clicked on Import GPX, the waypoints were ignored, and some imprecise locations were added to my photos. Here is an example: a 120-meter error:
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/5ab05cef-76ff-44e8-8661-edf8fea140c9)

expected coordinates
<wpt lat="56.81264499" lon="23.98148744"><ele>26.630</ele><time>2024-03-03T14:35:44Z</time><name>Most do</name><sat>36</sat></wpt>

but after GPX import function I got this - 56.813822, 23.980565

Here is my GPX file
[GPX file.zip](https://github.com/nemethviktor/GeoTagNinja/files/14499264/GPX.file.zip)

**Comment by nemethviktor** [comment]
The GPX import is generally handled by exiftool - as in there's a functionality for this in ET and GTN just functions as a wrapper around it. There's an option to display some logs but if you are ok to share the photo in question i can have a look at it later today.
My hazard guess is that the time interpolation/extrapolation is set incorrectly or the timestamp of the photo doesn't line up with your GPX file data. 
Eg if you look the line you mentioned is 
`<wpt lat="56.81264499" lon="23.98148744"><ele>26.630</ele><time>2024-03-03T14:35:44Z</time><name>Most do</name><sat>36</sat></wpt>` - now GTN only uses 6 decimals so you'll always have some discrepancy if you're expecting to see more than that but rounding but the one value pair that rounds to what you have is   `<trkpt lat="56.81382201" lon="23.98056499"><ele>30.581</ele><time>2024-03-03T14:46:11Z</time><speed>0.000</speed><sat>35</sat></trkpt>` -->round(56.81382201, 6) == 56.813822, round(23.98056499, 6) == 23.980565  so you might want to shift your time values by 11 minutes (?)

**Comment by NO-MAN-CAT** [comment]
> Can you have a test drive of https://drive.google.com/open?id=16laoPJcsJJz6mdkcjWvoQu6wWXiILbQy&usp=drive_fs pls -- that in particular to the two features you asked for (move to next button and paste). thnx

I deleted the existing version of GeoTagNinja and installed a 'new' one - 

1. Paste works as expected (I also think it would be good to add a 'question icon' and explain to the user that this feature is available.)
2. However the "move to next" button is always disabled for me

![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/b7c8a1d8-f2fe-45ce-994e-01e241e7138b)

**Comment by nemethviktor** [comment]
That's a feature not a bug :) -- you only have 1 picture so there's nowhere to advance - it's coded to be enabled only when 2 or more are available in the Edit Form. Select multiple pictures to edit. (CTRL+Enter or use the button for it.)

**Comment by NO-MAN-CAT** [comment]
> That's a feature not a bug :) -- you only have 1 picture so there's nowhere to advance - it's coded to be enabled only when 2 or more are available in the Edit Form. Select multiple pictures to edit. (CTRL+Enter or use the button for it.) Edit: the question icon has been added, it's on your screenshot ;) [just above the coordinates]

Oh, I see, "Apply & move to Next" is a little counterintuitive, but now I understand why it's done this way. 
After using GeoTagNinja for 10 hours, I discovered that there is a button to "Edit File"...
Usually, I just double-click on a photo to get the "Edit Data" pop-up. So combining the double-click with selecting photos using Ctrl or Shift will cause something like this -
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/db3be661-9a3d-4969-993a-c2402f3ff23e)

Thank you very much for adding these 2 features.

**Comment by nemethviktor** [comment]
It's not possible to click (single or double) on a listview _and_ retain multiple selected items because the listview click event in Windows is specific to the listviewItem clicked, so you'll need to do the selection and then either use the button or do Ctrl+Enter to get the multiple items into the Edit Form

**Comment by nemethviktor** [comment]
That's a little more problematic. Basically the context menu/paste (ie right click menu stuff) is a built-in functionality of Windows itself and while it's not impossible to waylay the process but I'd need to create a special instance of the `numericupdown`, which would be able to handle that. The issue is that there is a fair bit of code going into making sure that `numericupdown` controls work in a particular way and so basically changing the class of those two (but not the others across the app) would cause havoc I think, sorry.
