### ISSUE TITLE
Replicate destination lines in 'normal' mode

### ISSUE THREAD

**Issue by nemethviktor** [nemethviktor/GeoTagNinja#104]
I would also like to suggest another small "feature" where a line is drawn on the map connecting the selected photos - for example, if the user selects 3 photos, in addition to markers on the map, I would like to see a line to understand which marker corresponds to which photo.

Here is an example:
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/c0c78873-8b3f-4972-9e04-1d5e2e5cb175)

_Originally posted by @NO-MAN-CAT in https://github.com/nemethviktor/GeoTagNinja/issues/103#issuecomment-2007781853_

**Comment by nemethviktor** [comment]
Right so this one is actually kinda available **if** you have `destination coordinates` in your exif info. Not sure if you've tried that (?) - the way that works is that if you have groups of imgs with one constant destination then they'll be grouped on the map with lines leading to the destination,
If you'd still like this I can add it in as an optional thing (ie it wouldn't be auto-enabled but there'd be a new setting in Settings that would need to be enabled because I think for most users photos aren't really a path per se so making them appear "like paths" is a little dubious in my mind but it's not a difficult feature to add in.

**Comment by NO-MAN-CAT** [comment]
To be honest, I didn't understand your question.
Regarding the setting for drawing a line being disabled by default - great.
However, I've been thinking about what logic (code) should be used to draw the line, for example, what condition should be met to connect 2 photos using a line...
I see at least 2 ways of implementations:

**1.** Using file names - since photos have an increment in their names (each new photo has a number like DCIM10005, DCIM10006, DCIM10007), sorting by file names can be used to draw a line DCIM10005 --- DCIM10006 --- DCIM10007.
**2.** Using the time when the file was created.

**Comment by nemethviktor** [comment]
What I meant was that there are two pair of coordinates available in exif the "normal" latitude/longitude and the destination latitude/longitude. If you add destination to your files (should all have the same destination) then it should show the lines automatically. I would suggest you use that to be fair because there is a fair bit of existing logic to cover that.
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/8aeeb251-9c65-4421-82ae-c2d967950133)

**Comment by NO-MAN-CAT** [comment]
Hmm, I'm still having difficulty figuring out how to use this.
For example, I have 3 photos, and I would like to see the line, **but the Destination coordinates are not filled in.**
In order to see this line, do I have to select all 3 photos and manually assign the GPSDestLatitude and GPSDestLongitudes of the last photo to each one? This sounds strange.

https://i.imgur.com/6vXm4MV.png


I also don't understand how to do it because in the "Edit Data" popup window, there is no option to edit GPSDestLatitude and GPSDestLongitude attributes.

**Comment by nemethviktor** [comment]
It's under the map :)
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/54496bee-d15d-45a9-8291-5ee1db5b9576)
(last of the three) - select your files, then click on a point on the map and press that button. You might need to save.

The logic was/is that destination isn't likely to be manually entered bcs it's only supplied by certain gps models and so it'd either come filled in or user would mass-assign a point manually.

**Comment by NO-MAN-CAT** [comment]
> It's under the map :) ![image](https://private-user-images.githubusercontent.com/58767235/316606035-54496bee-d15d-45a9-8291-5ee1db5b9576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NjY3MzIsIm5iZiI6MTcxMTU2NjQzMiwicGF0aCI6Ii81ODc2NzIzNS8zMTY2MDYwMzUtNTQ0OTZiZWUtZDE1ZC00NWE5LTgyOTEtNWVlMWRiNWI5NTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE5MDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZDc5Yjc3NjBhZmU5NjEwNDNiODljNTQ3NTA4YjNkNGQ1NDgzOTNhZWI2ZTFmMjlhYTMzNGMzZmJlZDQ5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3MSbpXW7KH8pbpxKdB-aZt7VheH5iVwugy-K8Mv7BJ8) (last of the three) - select your files, then click on a point on the map and press that button. You might need to save.
> 
> The logic was/is that destination isn't likely to be manually entered bcs it's only supplied by certain gps models and so it'd either come filled in or user would mass-assign a point manually.

I see, just tested it and it works good! Feels extremely counterintuitive, but it works though.
Thank you for your efforts and explanation.
![image](https://github.com/nemethviktor/GeoTagNinja/assets/142752690/4fa28166-07cc-45cb-9014-cda95f27e5a3)

**Comment by nemethviktor** [comment]
If you have suggestions to make it less counterintuitive I am all ears - but remember that users have different workflows and some of the suggestions may not apply to everyone. 
For example re your comment re "lining up" images based on sequential names....in my personal case let's say I go on a holiday and then take say 1000 pics, many of which are duplicates or poor quality but I don't delete them on the spot. I get home and delete half of those. Then I split the rest by topic (say if I was to go to idk the solar system then some would be 01_Earth_img_xxxx, 02_Mars_img_xxxx (yes I know Earth isn't the first planet.) and so on. So now I have x number of photos that are by no-to-little logic sequential in their namings. Or I might have 2 cameras that shoot DSC_xxx and IMG_yyy [because why not one is a Nikon and the other isn't, or one is  defined in such way and the other isn't. Numbers are ofc misaligned.]  and I pair them up based on `CreateDateTime`, and so on. From a sequence perspective, total chaos.
So Destination isn't totally crazy because it can be sync'd easily. If you read the readme of the project there's a paragraph on how this logic actually works and it's relatively foolproof.
