### ISSUE TITLE
Export to GPX track file aka inverse geotagging

### ISSUE THREAD

**Issue by Kudolpf** [nemethviktor/GeoTagNinja#114]
**Request summary**
It would be very useful to be able to generate a GPX track file built from the gps data of existing geotagged images. In geosetter this is the _Export to GPX Track File_ option. In exiftool it is referred to as [_Inverse Geotagging_](https://exiftool.org/geotag.html#Inverse)
![image](https://github.com/user-attachments/assets/005ceeb6-7b4e-460a-9105-79c526935248)

**Why this feature is helpful**
It is not uncommon to capture geotagged photos on a phone alongside photos on a camera without GPS. For example when travelling I'll often use my phone for capturing mundane moments or for quick sharing online, but will use my camera when the situation calls for better photography. Constructing a GPS track file from the phone images is a simple way to correlate locations as often images will be captured on both devices at the same time and place. This is a reliable solution when when you haven't captured a more detailed GPS track through other means.
It is possible to create a similar GPS track using google timeline data, however this is more convoluted and less clean than using data from a selected set of images.

**Example solution workflow**
The workflow in geosetter works well, with a couple of possible areas for improvement.

1. Navigate to and select the images that contain the location data that you want to extract
2. Select the _Export to GPX Track File_ option
3. In the prompting dialog, choose some options for the file (more on these options below), and the file name and location to save to
4. A track is built and saved using the locations from only the images that were selected

**Options and considerations**
- **Field Selection:** Being able to choose which metadata fields are extracted and written to the GPX file would be very useful. For example, if the GPS date/time field exists than it is the logical choice to use for the date/time stamps, however this field does not always have data. HEIC images captured on common android devices for example don't populate this field, so you would need to be able to use a different field such as the Date/Time Original or the Date Created. Choosing whether to include altitude or not is another option that could be useful.
- **Time offset:** Relating to the previous point, the date/time stamps may or may not be in UTC time, which is required in the GPX file. This option would allow you to correct for timezones or incorrect clocks by adding or subtracting time from the chosen field before writing to the GPX. This is essential when the image doesn't contain GPS date/time data. (it is of course also possible to account for time offsets when importing a GPS track, but having correct data in the original track file is preferable!)
- **Data Sort/Order:** Rather than use the order the images are shown in the file browser, it would be useful to explicitly select the order the data points are arranged in. By default, using the GPS date/time field would be the most logical option, however there are situations where you may want to select another field to sort. You may want to sort by file name, or if multiple image sources or inconsistent names exist, sorting by date taken may be a better option.

Thanks for your work in creating this amazing tool, it's really been a massive help for me. Geosetter does not support HEIC images, which unfortunately are what most of my phone images are from the last 4 years. GeoTag Ninja has been a lifesaver, I've been using exiftool instead to create GPS tracks but if the function existed in GTN it would save me so much hassle and time!

**Comment by nemethviktor** [comment]
Hi, noted, I'll have a look next week most likely. 
In the meanwhile if you have some heic files that have the gpsdatetime in them that'd be great because i am not even sure that's being extracted at the moment [i don't have any apple products and hardly use my phone for photos...]

In particular re: sorting, some of that (especially the custom sort option) might be tricky. The ET documentation doesn't have info on custom sort beyond what's on the page you also mentioned, which isn't a lot. 
`exiftool -r -if '$gpsdatetime' -fileOrder gpsdatetime -p gpx.fmt pics > out.gpx`
...so I assume there is a way to do filename or some such but not sure about custom.

**Comment by Kudolpf** [comment]
Thanks! I don't have any heic files with a gpsdatetime, I'm using a samsung but it seems very device dependant which tags are saved. I've found some other [heic original samples](https://heic.digital/samples/) online, they all have different mixtures of data stored but none have used the gpsdatetime as far as I can see.

When using exiftool, I was doing a sort based on the CreateDate, and similarly I replaced the gpsdatetime in the gpx.fmt template to using CreateDate. I had to subtract the timezone offset to correct it to UTC time as the CreateDate option is a local time. Given that none of my files had the gpsdatetime tag I use an if check on gpslatitude to check whether that image should be used for creating the track file.
For reference, the command I was using was
`exiftool -r -ext HEIC -if "$gpslatitude" -fileOrder CreateDate -p gpx.fmt DIR > exportedTrack.gpx`

It looks like CreateDate and DateTimeOriginal are pretty universally used fields, so seemed safer to use this and just deal with time zone offset somewhat manually for the gps time.

The main [fileOrder](https://exiftool.org/exiftool_pod.html#fileOrder-NUM---TAG) options I imagine I'd use would be CreateDate/DateTimeOriginal, or FileName (possibly inverted, by using a - before the field name)

**Comment by nemethviktor** [comment]
Can you have a play with this https://drive.google.com/open?id=16laoPJcsJJz6mdkcjWvoQu6wWXiILbQy&usp=drive_fs please and see if it largely does what you're after? (same place as the import feature just a new tab.)
The UTC conversion is actually automatically done inside ET (assuming there's a time `offset` value so you won't see it being shown.

**Comment by nemethviktor** [comment]
Hi @Kudolpf , can you have a look at the above please;)
