### ISSUE TITLE
http links

### ISSUE THREAD

**Issue by paddotk** [nemethviktor/GeoTagNinja#117]
**Describe the bug**
Links from the readme here on Github as well as the software itself, that link to geonames.org, refer to http://www.geonames.org, not http**s**//www.geonames.org. The website does not redirect to https either. This is not so much a bug perhaps, but more a security concern, as logging in via http isn't safe.

**Comment by StarGeekSpaceNerd** [comment]
From what I can see, while the main page isn't https, the moment you try to log in you are switched to https

**Comment by nemethviktor** [comment]
Not sure it works tbh. 
If you look at for example `https://api.geonames.org/findNearbyPlaceNameJSON?formatted=true&lat=51.52288&lng=-0.158996&lang=local&style=FULL&radius=10&maxRows=1&username=yourusername&password=any`

it will return a `NET::ERR_CERT_AUTHORITY_INVALID` error.

if you proceed you just get a `Not Found -- The requested URL was not found on this server.` (404)
