### ISSUE TITLE
freeze on browsing to folder

### ISSUE THREAD

**Issue by andrew-spink** [nemethviktor/GeoTagNinja#118]
**Describe the bug**
The programme gives an error message and then freezes when I browse to some folders

**To Reproduce**
1. In the file browser, go to folder D:\Documents\Stack\Slides- Stack\35001-35101 (NB e.g. D:\Documents\Stack\Slides- Stack\5501-5600 gives no problem)
2. Programme gives error message (see screenshot)
3. On clicking Ok, programme freezes

**Expected behavior**
Image files in that folder shown in browser (NB there are no other files there)

**Screenshots**
![image](https://github.com/user-attachments/assets/a301bebb-2c91-40ab-a9f1-1f2b7354ccfc)

**Desktop (please complete the following information):**
 -Windows 11 Pro version 23H2, 64 bit
- Processor 13th Gen Intel(R) Core(TM) i7-13700H   2.40 GHz

**Additional context**
Worked ok previously
Tried reinstall to latest build, that didn't help.

**Comment by nemethviktor** [comment]
Hi,

You seem to have a space in that folder name, does it exist as such?
I tried recreating your folder path and it works ok. If I add another space to try to point to a location that doesn't exist then the message comes up, although admittedly there's no way out of it. 
I can add an option to allow an explicit revert to something like C:\ and then not be in an infinite loop (?)

**Comment by andrew-spink** [comment]
It seems to be caused by the presence of the enclosed file in the folder. Perhaps there is something wrong with its EXIF data that causes the freeze?
![35044](https://github.com/user-attachments/assets/bc3010c2-a1a0-4822-95da-f0447f4ea7ed)

**Comment by nemethviktor** [comment]
Right, yes, so oddly enough the file has no coordinates but it does have an `unknown()` gpslatitude reference (which should be something like `North`, assuming there are coordinates in the file), which was causing the issue.
Can you try this one https://drive.google.com/open?id=13uYyCQE31JlSUb2iamKdYh55bGNqQFOW&usp=drive_fs

**Comment by andrew-spink** [comment]
That seems to have done the trick!

Thanks!

Andrew
