### ISSUE TITLE
"Restart Now" after changing Settings doesn't restart GTN

### ISSUE THREAD

**Issue by ForgeSource** [nemethviktor/GeoTagNinja#119]
**Describe the bug**
After changing some Settings, I am prompted to restart, but choosing "restart now" does not restart GeoTagNinja.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to _Settings > Settings_
2. Click on (for example) _"Use Dark Mode in the App UI?"_
3. Click on _"OK"_
4. Click on _"Restart Now"_ in the resulting dialog box
5. GTN closes, but does not restart

**Expected behaviour**
GTN should close and then restart.

**Screenshots**
Can provide, if they would help.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro build 22621
 - Language/Culture: en-GB
 - Full Path of Picture: N/A

**Additional context**
Very low priority.
Not sure whether "Restart Now" is actually meant to mean "GTN will shut down now, and you will need to restart it manually"?

**Comment by nemethviktor** [comment]
I was wondering when people would notice that :D
Try this version pls. https://drive.google.com/open?id=13uYyCQE31JlSUb2iamKdYh55bGNqQFOW&usp=drive_fs

**Comment by ForgeSource** [comment]
Yes, I can confirm that this version fixes it.
Thank you for such an amazing fast response!
