### ISSUE TITLE
no folder should be selected on first opening

### ISSUE THREAD

**Issue by unosakk** [nemethviktor/GeoTagNinja#120]
**Describe the bug**
Opened the app for the first time and the application chose my onedrive with cloud only pictures. It is now downloading them on to the device for geotagninja to use. it serveral G on pictures ...

**To Reproduce**
1. Open app

**Expected behavior**
user can choose the folder?

**Screenshots**
![image](https://github.com/user-attachments/assets/ae6d93af-86ae-4c4a-abc9-2f45875c2a91)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Language/Culture en-US
 - Full Path of Picture: C:\Users\unosa\OneDrive\Pildid

**Additional context**
Canceling download crashes the app
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at GeoTagNinja.Helpers.HelperExifDataPointInteractions.AdjustLatLongNegative(String point)
   at GeoTagNinja.Model.TagsToModelValueTransformations.T2M_GPSLatLong(ElementAttribute attribute, String parseResult, IDictionary`2 parsed_Values, Func`2 ParseMissingAttribute)
   at GeoTagNinja.Model.DirectoryElement.ParseAttribute(ElementAttribute attribute, IDictionary`2 parsedValues, List`1 parsedFails, IDictionary`2 tags, Int32 callDepth)
   at GeoTagNinja.Model.DirectoryElement.ParseAttributesFromExifToolOutput(IDictionary`2 dictTagsIn)
   at GeoTagNinja.Model.DirectoryElementCollection.ParseFolderOrFileListToDEs(String folderOrCollectionFileName, Action`1 statusMethod, Boolean collectionModeEnabled)
   at GeoTagNinja.FrmMainApp.lvw_FileList_LoadOrUpdate()
   at GeoTagNinja.FrmMainApp.<FrmMainApp_Load>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GeoTagNinja
    Assembly Version: 1.15.8973.39526
    Win32 Version: 1.15.8973.39526
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/GeoTagNinja.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
CommandLine
    Assembly Version: 2.9.1.0
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/CommandLine.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.2.3.1999
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/NLog.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.118.0
    Win32 Version: 1.0.118.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.2535.41
    Win32 Version: 1.0.2535.41
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
CsvHelper
    Assembly Version: 30.0.0.0
    Win32 Version: 30.0.1.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/CsvHelper.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.53103
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.2535.41
    Win32 Version: 1.0.2535.41
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by nemethviktor** [comment]
Hi, 

You can set the default folder in Settings
![image](https://github.com/user-attachments/assets/ebbebce7-161f-4a31-9d56-a47b99032675)

We can't have "no folder" as a default I'm afraid, the assumption is that there _is_ something defined for the app to start in. Currently the default is the user's "Pictures" when nothing is set. While I could change that to something like "My Computer", it's a little awkward and the users can change it after the first launch to whatever works for them.

As for the crash I think that has been fixed in a yet unreleased version https://drive.google.com/open?id=13uYyCQE31JlSUb2iamKdYh55bGNqQFOW&usp=drive_fs

**Comment by unosakk** [comment]
already deleted my onedrive from the pc and got in without a crash. Can´t test the unreleased version. 

Didn´t find any easy way, to change that onedrive is not the default picture directory. For my case using picture is the worse option then "my computer". But it´s the developers choice. I quess using and seperate conf fail for startup folder parameter isn´t a better solution .

**Comment by nemethviktor** [comment]
Why don't you set a default in Settings as per screenshot?

**Comment by unosakk** [comment]
It crashed before going to settings was possible.
If the crash is fixed. It should be okey now for onedrive users. If i but onedrive back, i aill try to remember and test

**Comment by nemethviktor** [comment]
See if it works with the unpublished version. If still not I'll dig into it a bit more.
Btw technically there is a settings file, more precisely after install, upon the first launch it gets created at `c:\Users\username\AppData\Roaming\GeoTagNinja\database.sqlite`

You can try something like modifying the value in `settings`
![image](https://github.com/user-attachments/assets/79ca60d1-4aa7-4e48-ae21-0046f7d885cb)

but it might be a little tricky if you're not familiar with sqlite stuff.

**Comment by GWL20** [comment]
Dealing with which folder to open on start of the program does not solve the main problem here. 
I would suggest to seperate selecting the folder and parsing the files in two distinct actions. Starting "parsing folders and files" should not be automatic but a user interaction after having selected the folder.
In addition, it would be very helpful if the parsing process could be stopped in case you have inadvertently selected a folder with thousands of files.

**Comment by nemethviktor** [comment]
Hi,

The request for a cancellation token is valid and I'll try to add it in at
some point.


Specifically though re: entering a folder and not parsing it won't make
much sense/use if your problem comes from OneDrive pulling data randomly.
Two alternatives exist here that would define possible behaviour:
1) if the user enters the folder and we don't event list files at all then
it's just a blank grid and nothing else. I don't think anyone apart from
you'd would want that and even in that case the cloud  software might start
caching the contents.
2) user enters folder and we only list the files themselves (ie the names).
This will definitely trigger the cloud software to download the data.
This message has been brought to you by my Honor Magic5 Pro and myself. Any
typos blame the phone.

**Comment by nemethviktor** [comment]
Hi again, 

I've added the CTS to the folder loading, not quite sure when I'll do a release (prob soonish at some stage) but can you check pls in the meantime. -> https://drive.google.com/file/d/13uYyCQE31JlSUb2iamKdYh55bGNqQFOW/view?usp=drive_link
