### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by draft-jay** [nemethviktor/GeoTagNinja#125]
**Describe the bug**
cannot save ,because of Chinese I guess

**Screenshots**
![image](https://github.com/user-attachments/assets/ade98bf6-ad01-4303-b1a3-2543cf1e65c9)

**Comment by nemethviktor** [comment]
![image](https://github.com/user-attachments/assets/fbc8f0e5-72d0-47d7-afdf-2ed459ce4950)

I've had a look at this and if you enable the Unicode setting as per above it works. Note the first image having a different altitude value (83) than the rest (82), which was successfully saved in the folder with Chinese characters.
