### ISSUE TITLE
no information about new release

### ISSUE THREAD

**Issue by pbranly** [nemethviktor/GeoTagNinja#14]
Hi,
I currently have the version 0.6.8350. At start up I should receive a notification for downloading the last 0.6.8358
But no info
Regards
Phil

**Comment by nemethviktor** [comment]
![image](https://user-images.githubusercontent.com/58767235/202845514-c18e6193-e4aa-4735-bb58-b43447009a40.png)
https://github.com/nemethviktor/GeoTagNinja/releases/tag/v0.6.8358

This doesn't work?

**Comment by pbranly** [comment]
For sure it works but my understanding was that starting the current
version, I should receive a notification that a new version exists with the
link.
Phil

Le sam. 19 nov. 2022 à 11:04, nemethviktor ***@***.***> a
écrit :

**Comment by nemethviktor** [comment]
Yeah but what's the link that you got and it didn't work?

**Comment by nemethviktor** [comment]
Ahh I get what your query is. Yes and no.
There was a change in one of the earlier versions that the new-version-query only runs once a week. That is so that the APIs don't get hammered all the time.

**Comment by StarGeekSpaceNerd** [comment]
Alternatively, you can watch for releases on Github and receive an email when there's an update.

![chrome-2022-11-19_06 19 19](https://user-images.githubusercontent.com/27904711/202855510-2555a3b1-de26-476e-9251-e45c39d0a5fa.png)

**Comment by pbranly** [comment]
Thanks but I was already registered in your GitHub in order to receive anything ! 
phil

**Comment by nemethviktor** [comment]
Tempted to close this. I've checked in code and it should work okay. 
The logic is currently that it only checks once a week against your current version - considering that you tend to use whichever development version there is, it's unlikely you'll ever get a notification before it hits github! :)
Reopen if needed.
