### ISSUE TITLE
Reverse geocoding not working

### ISSUE THREAD

**Issue by GWL20** [nemethviktor/GeoTagNinja#146]
**Describe the bug**
No Country/city/.. information is downloaded.

**To Reproduce**
I have created a GeoNames account and entered the credentials in "GeoNames Settings"
When pressing the "Get Toponomy.." the following messsage appears: "GeoNames API Returned the following response:" after pressing ok, the error message "Failed to reach the API - are you offline by any chance?" is shown.
The geonames.org website works with my credentials.

**Desktop):**
 - OS: Windows 10 pro 22H2
 - Language/Culture: de

**Comment by nemethviktor** [comment]
Try again. :)
I've had that before. But basically it's an issue on the API side. If the value that it sends back is comprehensible it gets processed, otherwise if there is an error message, it's shown. For some reason sometimes it just returns a totally empty message.

**Comment by GWL20** [comment]
Thank you for the lightning fast response.
I could display the error message via the file's context menue "open coordinates in API": ""user account not enabled to use the free webservice. Please enable it on your account page: https://www.geonames.org/manageaccount ". This is a box just under the login credentials. Now it works.
