### ISSUE TITLE
[Feature Request] Edit dialog to change attributes (date+time captured) of an image

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#18]
Hi @nemethviktor,

is it ok to also file feature request...? I just stumbled accross this one while going through my usual tagging workflow.

**I would like to by hand modify the date (and time) the image was captured.**

As I was not able to do this with system standard tools and it seems to me like a thing that one would like to do in such an app. I open this feature request.

Maybe it also makes sense to add other attributes that can then also be modified by the user.

**Comment by nemethviktor** [comment]
Yeah, feature requests are ok :)
This one will come a bit later, I basically would like to debug the two things you flagged plus I already have a commit list of 7 other smaller or bigger enhancements but need to test them a little first.

**Comment by nemethviktor** [comment]
Hey, can you have a test drive pls. [link](https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link)

**Comment by Urmel** [comment]
Hi @nemethviktor,
wow - that was fast!
I'ld love to test the new feature. But it either is too late and I can't see my mistake or the linked file actually installs an older version:
![grafik](https://user-images.githubusercontent.com/1786902/204062996-25dba092-abce-414d-8317-297c13735a17.png)

SHA256 of installer file I used: 8FC390A7CC2C5A7D87C775049438E2FA56F8CFE2D267F1FFE66CE3359AB3566D
Size of it:
![grafik](https://user-images.githubusercontent.com/1786902/204063095-f55bad90-a9ef-434a-8c7e-35e7a0c19a53.png)


(I uninstalled all previous versions before...)

BR
Alex

**Comment by nemethviktor** [comment]
That is the newest one. Remember my time zones are UK time zone so if you're expecting "midnight" because it was midnight your time when I posted, you won't find one ;)

Go to Edit file (just the edit window), it should be there.

**Comment by pbranly** [comment]
Hi
I just tried but didn't notice any difference
What do I need to look for ?
Phil

Le ven. 25 nov. 2022 à 23:15, nemethviktor ***@***.***> a
écrit :

**Comment by nemethviktor** [comment]
See screenshot above - in the Edit File section there's a new tabPage called Date & Time

**Comment by pbranly** [comment]
Sorry i wouèld have look at better !
I forgot to change the time settings in my camera after the winter time change and so had all my photos taken with a bad + 1h time diference.
In addition, the exiftool has a offset field that is +2 hours (I assume UTC+2 rather than UTC+1)
It seems that I cannot change that field
![2022-11-26_10-07](https://user-images.githubusercontent.com/22018509/204081361-84eb63d4-21a3-42c8-b9a4-b2bfc919ff6d.png)

I also tried the date modification: it works for a single photo but not for a selection of photos.
It is possible to select a batch of photos, then go to the date modification menu, change the date or introduce a time difference but the result is only for the selected photo in the menu.
In geosetter, it was possible to select a batch of photo and apply a new date or select a time difference and all the selected photo were date modified by respecting the relative time difference (this as well the way Lightroom works when changing the date of the photo)

Perhaps too complex ..... honestly even in geosetter this feature is treaky to use !

Phil

**Comment by nemethviktor** [comment]
Yes, TZ modification isn't on the list yet :) -- it's an "upcoming feature". 
Atm I'm debugging something else and then I'm AFK (away from keyboard) for the weekend as usual. 

I'll ponder on the mass-time-shift somehow. The current logic is that whatever is in the DateTimePicker (you'll guess which one that is) is what the data ends up being. So "shift" is just shifting the DTP, not the values really. It's easier to code. ExifTool can in fact do shift, and it's a relatively easy change.

I'm more tempted to 1) add in TZ-change logic and then 2) edit the CopyPaste logic and allow for copypasting the Time Zone. Easier to deal with. 
Also I think the geosetter logic of having a "get from web" button for the TZ is silly. It should be part of the "get from web" on the location side. Basically when pulling location details it should pull the TZ automatically. This would make everyone's lives a lot easier. The code already has some logic to allow for this but it's hidden atm because it's incomplete.

(atm = at the moment)

**Comment by nemethviktor** [comment]
This is more of  a heads-up (and actually I checked GeoSetter worked the same, or it defaulted to local (computer) time zone, or just randomly GMT, not entirely sure). I haven't uploaded this yet to google drive so don't yet look for it, however...Time Zones (in the Edit File) will be left as blank on open regardless of what the stored value is. There is no Exif Tag for TZ but only "Offset", which is something like "+01:00". As there is no indication for neither TZ nor DST per se I can't ascertain that  "+01:00" was in fact say BST rather than CET, one being DST the other not. Either adjust manually or pull from web - the combination of coordinates + createDate would decisively inform the program of the real TZ value.

**Comment by pbranly** [comment]
I agree 
I don’t think this field has any rule when importing gps coordinates . When I modified my mistake and change all dates minus 1 hour, the software could find correct localisations while it did not with the bad time, despite the fact that this field was kept as +2 hours.
So I think this is a feature with a wry very small priority equal to zero !
phil

**Comment by nemethviktor** [comment]
Usual link, can ppl test pls. 
I've also updated things relating to "get from web", "get all from web" and some of the occurrences thereof.
Also the copypaste.

**Comment by Urmel** [comment]
Hi @nemethviktor,
I downloaded and did a few tests with this version:
![grafik](https://user-images.githubusercontent.com/1786902/204373699-1de1d1d8-9d62-44a9-8966-aff49b907ed5.png)

Thanks for this cool new improvement.

Some improvement **ideas**(!):
- The button "remove all location data" is located inside a frame called "location" (like the get / all from web) but is applied to both frames (location and GPS) ... I'm not sure about the use case for that button, but with given functionality I would suggest placing it outside the frames and renaming it to "remove GPS and location data".
- Maybe set a title above the image list in the edit window - something like "Images selected for editing". Then the button "Set current values for all images selected for editing" would be very consistent. I first (briefly) was thinking about I need to select multiple images in this sub list.
- "Set values for all selected images" does not lead to image file names going red (as they do when using "get all from web"). For consistency reasons they probably should.
- I do not get the difference between "get from web" and "get all from web" at first. Maybe rename to "Get for all selected images from web" or make a frame aroung it "Get Altitude data" with buttong "for this image" and "for all selected images" ...
- I do like the idea of the TZ being part of the location. Sadly only the Offset is saved and not the selected time zone ;)

### Question: is it intended behavior that only the sidecar is updated if there is one?

GeoSetter updates both files if there are such and if there is no side car, it creates one (maybe due to my config, though). Maybe we should give the option to at least update both...

### Issue: One can select countries as a TZ leading to string in TZ-TUC-Diff
In the lower part of the drop down there seem to be countries. When you select one of the, their name is transferred to the numerical box:
![grafik](https://user-images.githubusercontent.com/1786902/204378304-220a1926-207a-483d-a59f-dddf23100337.png)
... this also is carried over to the FileList:
![grafik](https://user-images.githubusercontent.com/1786902/204378381-b17de838-6990-4cde-be4c-83a60d148534.png)
... but obviously leads to error when trying to save:
![grafik](https://user-images.githubusercontent.com/1786902/204378476-5cf9b972-ddb0-421f-a929-234d1ce47706.png)

**Comment by nemethviktor** [comment]
Okies, kind of in order....
- I've changed the About box so Version is now selectable.
- Moved & renamed the Remove Data button inside Edit
- re: "Images selected for editing" -> ok
- re: boxing up "get all data" -> ok
- re: time zone setting: not possible, sorry (see the "?" mouseover)
- re Honduras etc: Ehh lol ok I haven't noticed those. Derp. Thanks for the heads up. Deleted.

Re your Q on sidecars. Check file settings. :)
![image](https://user-images.githubusercontent.com/58767235/204482714-7a80cea4-4a8e-4f57-9ea0-13b8a798fdf9.png)

**Comment by pbranly** [comment]
Hi
I am lost with the version and the modifications;
I have downloaded the last version this morning and can't find the differences


Version: 0.6.8368 [20221129:1643]
I've changed the About box so Version is now selectable.  ----------> where ?
![2022-11-30_13-49](https://user-images.githubusercontent.com/22018509/204800714-a39d32e5-1c72-48b1-ac09-6d09b0a540ce.png)

Moved & renamed the Remove Data button inside Edit: ------> seems always at the same place

![2022-11-30_13-51](https://user-images.githubusercontent.com/22018509/204801003-ea0d31e9-afa6-418c-98ef-280997acac42.png)


Phil

**Comment by nemethviktor** [comment]
Hi Phil, 

> I've changed the About box so Version is now selectable. 
You've just found it! :) - the rest can't be selected. Alex was asking that he wanted to copypaste that rather than having to screenshot-crop each time.

> Moved & renamed the Remove Data button inside Edit
You're not looking at/in Edit.
![image](https://user-images.githubusercontent.com/58767235/204805981-30847d6d-38bf-492f-9581-ededff914d74.png)

**Comment by pbranly** [comment]
Ok that’s clear 
For the remove data button, my (French ) understanding was that « move » was more in the « cut and paste » than « copy and paste » 
Your program is better and better 
I m surprised that no German people proposed their translation yet. 
Phil

**Comment by nemethviktor** [comment]
Haha no worries. :)
The reason for the many updates is that _i am_ using the software....and as such I'm finding a lot of inefficiencies and annoyances. I now have some 20 commits queued up. Mostly around making things faster.

**Comment by pbranly** [comment]
That’s true that since the last version, the photo loading is very long ( but ok) . I assume you fill some cache

**Comment by nemethviktor** [comment]
Actually don't use that one just yet, sorry. Pasting overwrites things it shouldn't.

**Comment by nemethviktor** [comment]
Right, new new version - apologies about that one. Should work I think [TS 1645-ish]

**Comment by pbranly** [comment]
Hi
anything new for editing a batch of photos ?
i tried to select 20 photos
edit file, date and time
create date taken , time sshift -2
define for all pictures
create date
ok ok
but they are all modified with a fixed time

Phil

**Comment by nemethviktor** [comment]
Not yet. I'll try to get around to that this week.

**Comment by Urmel** [comment]
> This is obvious but assume that the user comes and goes between folders and re-enters a folder they've already been to during the session. In that case there is no point in re-reading _all_ the file data _again_, but only for stuff that may have changed. In whichever version I was comparing the timestamp of files to whatever is held internally in the app. The problem is that if the user choses (in the settings) not to update the fileModifiedTime (more precisely pull it from createDate) then that value never changes and the app can display outdated values.
> 
> So now we're hashing the files with an MD1 hash. This is slower but still generally faster than reloading everything each time. I need to ask Phil H if there is any particular logic as to where in a random file the tags are kept (like beginning, middle or end) so that I can just hash (say 100kbytes) from a few places rather than reading through RAW files that could be 80mb each.

...

> Not yet. I'll try to get around to that this week.

Hi @nemethviktor,

I would propose to try to squeeze out a release with the current feature set running correctly. There are quite some changes since the last release. Performance and further features would then be a follow up. In a follow up you could also accept some PRs - I have some ideas on UI improvements that I could contribute on a current code base.

If you like, I can also create a request for the speed improvement when entering a directory.

BR
Alex

**Comment by nemethviktor** [comment]
Hi @Urmel thanks for that offer:)
I'm out and about now but yes tempted to do a release tomorrow morning and then continue with the work?

**Comment by Urmel** [comment]
Your choice master :)

**Comment by nemethviktor** [comment]
Lol - "master". Did I tell you I never actually wrote anything in C# before? :D 

Anyway. @pbranly there is a new public release out now. That _doesn't yet_ have the shift-copy-paste thing. A TLDR is that everything works on an exifTag basis and shifts...well they do not constitute as one (there is no such tag) so I have to write logic around the whole thing.

@Urmel I'll have a look at your original PR today. :)

Btw the release today is ever-so-slightly different from the one yesterday evening on/in the dev folder. I removed FileModifiedTime from the columns as it was triggering some fuckery with the AsyncExifTool class/addin and I didn't want to include it.

**Comment by nemethviktor** [comment]
Just a heads up for anyone that might care that this is now well in progress and unless I get dragged into it something else tomorrow I should be able to produce a version that does time-shift-copy-paste.
I realised that my initial code logic for handling tags (or the lack of them, in this case) is a lot more lenient than I remembered (call that beginners luck I guess) so it's less of a pain in the backside than I expected things to be.

**Comment by nemethviktor** [comment]
Right, posted a file on the dev-google-drive-link, can you all have a look please. (TS likely now-ish so 2155 UK time. There was one earlier today but I realised it didn't quite work as intended.)
I'll try to clean up the code a little over the coming few days bcs this change has introduced a fair bit of redundancy.

**Comment by pbranly** [comment]
Hi this version crashes and it is very difficult to crash the application
to come back to windows
Regards
Phil
[image: 2022-12-07_13-31.png]


Le mar. 6 déc. 2022 à 22:57, Viktor Nemeth ***@***.***> a
écrit :

**Comment by nemethviktor** [comment]
hi Phil, 

There wasn't a screenshot attached so I can't debug. Where does it crash as it works ok on my French VM?

**Comment by pbranly** [comment]
Sorry mail was not fully uploaded and I resend it.
Phil

**Comment by pbranly** [comment]
![2022-12-07_13-31](https://user-images.githubusercontent.com/22018509/206208195-dc37e4bc-69cd-44ae-92e8-346e326e82eb.png)
it happens when opening a directory with photos

**Comment by nemethviktor** [comment]
Thanks - nah, it's something about datetime conversion. I don't presume you could copy the whole folder as-is to someplace? You can email me a link. 

There must be a file or two that have odd datetimes in them. I tried with a "random" one plus one that had the data removed but they're ok.
![image](https://user-images.githubusercontent.com/58767235/206210775-8a4c05f3-7c2e-4464-93c3-a61b23f9441a.png)

**Comment by nemethviktor** [comment]
nvm, don't send. Found one that in fact crashes. Will investigate.

**Comment by nemethviktor** [comment]
Okies, try now (new version just pushed to GD)
I'll start working on some internal logging in the meanwhile, I'm trying to figure out why certain things are soooo slow. (namely the Edit File Form being opened.)

**Comment by pbranly** [comment]
Hi it works
Thanks
Phil

Le mer. 7 déc. 2022 à 19:21, Viktor Nemeth ***@***.***> a
écrit :

**Comment by nemethviktor** [comment]
hi @Urmel  can you pls confirm you're happy with how this works (or not?) in the current dev version?
Thanks

**Comment by Urmel** [comment]
Hi @nemethviktor,
I've been away for some days - I take it that I should test the binary (it's not in DEV branch)?
BR
Alex

**Comment by nemethviktor** [comment]
I can confirm that the code on my side is up to date. My last check-in/diff to the Dev branch is the current version of the code. [does that answer your Q?]

**Comment by Urmel** [comment]
Hi @nemethviktor,
thanks for the new version. I had a look at it and it has all the features that I was looking for. The editing itself is quite smooth.

There were missing some localizations in the SQLLite - I added / fixed the english ones that I became aware of manually. I guess you should do a export of the Excel (where I added the column stuff, but I don't have a sqlite odbc installed ;)). In additon, some french translations are open (I did not fill them).
PR/Commit coming in a minute.

In my perfectionistc world, when clicking on "Set current values for all images selected for editing", the dialogue would already be preset by the changes that I have applied to the current image. For example if I set a time shift, the dialogue already sets the Taken Date with time shift option to be rolled out.
Does that make sense?

So thanks!

**Comment by pbranly** [comment]
Hi I will take care of the French side is the file is stable enough .
Please advise 
Phil

**Comment by nemethviktor** [comment]
31a24662128ecdb17b186a6d47c2e48d62e15378

**Comment by Urmel** [comment]
You are fast!
I love it :)
