### ISSUE TITLE
When going from maxed window to normal size panels arrange strangely

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#19]
### Setting
- Latest greatest provided in this issue: https://github.com/nemethviktor/GeoTagNinja/issues/15.
- Running on a German Win10 machine.

### Error

When the app has its window maximized, one can resize it to "normal" in two ways:
- Pressing the reduce size button in the upper right
- Pulling down on the title bar

Taking the first approach (reduce button), I can change the size between max and normal. I can also - when in normal size - resize the window by dragging the lower right corner. --> Fine.

But using the second approach (title bar), it reduces it sizes and re-arranges the panels in a funny way:
![grafik](https://user-images.githubusercontent.com/1786902/203172208-b6add4d1-96a9-4580-8a54-bd69b3fe6eed.png)

- The effect seems to be bigger when the initial reduced size (directly after pulling on the title bar) is smaller.
- The effect seems to have a varying degree of "severity".
- The effect cannot be healed by (multiple times) bringing it to max size and reducing the size with the button again.

### Workaround

Use the resize button to change from max to normal size.

**Comment by nemethviktor** [comment]
Made another update to the same location (ie overwrote) as the one in the afternoon https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link
See if it works better now.
Also I've been silly enough (not on purpose) to mix up the ProductCodes - basically if you've installed the one in the afternoon then you'll prob have to explicitly uninstall that one, sorry.

**Comment by Urmel** [comment]
Hi @nemethviktor,
you are fast! Thanks a lot for the quick reply and the effort you put in this. Wow!

I downloaded the msi provided (it says version 0.6.8361) and with it **could not reproduce the issue again** (did a few app restarts and wild resizing).
