### ISSUE TITLE
increase field size 

### ISSUE THREAD

**Issue by pbranly** [nemethviktor/GeoTagNinja#26]
increase field size in settings
![2022-12-09_12-25](https://user-images.githubusercontent.com/22018509/206692686-0a71f4b5-4d82-49d6-b279-16a32b8f5763.png)
Thanks
Phil

**Comment by nemethviktor** [comment]
Fixed just now -> [7deab7d](https://github.com/nemethviktor/GeoTagNinja/commit/7deab7d2de62c55cb9e3ba224a667ddce7967711) 
See usual google drive link pls. [here](https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link)

**Comment by pbranly** [comment]
Fixed thanks
