### ISSUE TITLE
Installation shortcut self-references

### ISSUE THREAD

**Issue by TWCunningham** [nemethviktor/GeoTagNinja#3]
Forgot to mention, but when I use the .msi installer the shortcut for the start menu points back to the folder where the shortcut resides (e.g. for me, C:\Users\Tom\AppData\Roaming\Microsoft\Windows\Start Menu\Programs), instead of the executable (C:\Program Files\GeoTagNinja\GeoTagNinja.exe).

**Comment by nemethviktor** [comment]
I've seen that on one of my virtual machines but works okay on my main one. Will try to do some digging as to why. I'm using Visual Studio Setup Project which is a pain in the backside. Will report back soonish.

**Comment by nemethviktor** [comment]
Right, found the issue. I'll close this as it will be pushed along with the next release at some stage. Not sure why but VSI (the installer) defaults the Start Menu shortcut to the app's folder, which is pretty stupid but alas. Changed it now (not released yet.)
