### ISSUE TITLE
[Feature] Adjust Column Sort Order for File List to Handle Folders Differently

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#30]
## New Sorting Rule: Folders, ".." and drives should always come at the top
Whatever column, we sort by, we should keep folders and ".." at the top (and in alphabetical order).

## Implementation Proposal

In order to implement this, I propose to create an object model containing the image information. For a start just the info on type and name. The longer term idea is to migrate the other data also into this model. This will allow us to easily extend it, implement logic and caching (preview images for example) in it and also allow for an encapsulted functionality to track changes to the single objects.

The other option would be to use the methods as used in the image preview / generation, where for folders or alike, no images are generated.

**Comment by nemethviktor** [comment]
Sounds good to me - however I'll be dead honest with you I think you're better placed to do this or at least start. I'd need to loo up what an object model is, in general, which says a lot ;)

**Comment by Urmel** [comment]
> Sounds good to me - however I'll be dead honest with you I think you're better placed to do this or at least start. I'd need to loo up what an object model is, in general, which says a lot ;)

I'm no pro either, but I have an idea where I want to get to with that. Yeah - I'll start and we then can extend as we wish...

**Comment by pbranly** [comment]
Oups don't ask me to make and code !
I can make feed backs about the behaviour of the program. But that's all
And those remarks could be accepted or not for sure with other users point of view

Phil

**Comment by Urmel** [comment]
Hi @nemethviktor,
I seem to be a little to slow for your pace ;) Sorry.
So if you still want the contribution, I will look into refactoring this into the model-thinging I was refering to above...

**Comment by nemethviktor** [comment]
No worries haha - if you think having the object/model logic in the long term will be beneficial the yeah definitely if you're willing start work on it ;)

**Comment by Urmel** [comment]
Hi @nemethviktor,
in the PR for the DirectoryElement, I also prevented the user from reordering the first column - as changes to it were not saved / recovered anymore.
