### ISSUE TITLE
Better map resolution?

### ISSUE THREAD

**Issue by TWCunningham** [nemethviktor/GeoTagNinja#4]
I can't zoom in as much as I would like on the map to pinpoint a location.  Any way to get closer?

**Comment by nemethviktor** [comment]
Sorry, that's a negative. It's in the readme but it's a limitation of openstreetmaps I think. If you want you can try to fiddle around with the map.html (just save a backup), there is a default zoom level in it but I've tried it and if you change it to "zoomier", it won't actually do much after a certain level.

**Comment by TWCunningham** [comment]
Great tip, I changed the maxZoom to 19 in map.html and that zoomed in plenty for me.  I tried 20, but that makes the map sort of "blow out" past what you get at 19.  I also fiddled with the zoom parameter in the L.map('map').setView call, which makes for a nice default view of the map on startup.
