### ISSUE TITLE
version 0.7.8391 cant update photos

### ISSUE THREAD

**Issue by pbranly** [nemethviktor/GeoTagNinja#47]
Hi 
Happy new year.
I just try to update photos with gpx positions without success
i select all the photo and select either the gpx file or the directory where the file is and click on OK
the OK becomes grey and even after several minutes, i dont have any result
The solution is to click on the "Cancel" button but there is not any photos updated and no message

Phil
![2023-01-04_12-52](https://user-images.githubusercontent.com/22018509/210549575-6093b2bf-145f-4da9-ad47-ce1035efe83f.png)

**Comment by nemethviktor** [comment]
hi Phil, 

Happy new year!
As per usual I'll need at least some of the photos that don't update as well as the gpx files themselves. Email me if that's more convenient pls. 
Thanks

**Comment by pbranly** [comment]
In fact it works as long as there positions in the gpx file for ALL the
photos;
in case there is only one photo without position in the gpx file, it hangs
Please find one of those photos in a private mail
Phil

Le mer. 4 janv. 2023 à 13:04, Viktor Nemeth ***@***.***> a
écrit :

**Comment by nemethviktor** [comment]
Ta. (that's thanks, in case not familiar ;))

I've uploaded a new version just now to the usual -> https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link

Admittedly not 100% sure this will solve the issue but I _think_ it would. Have a look pls?

**Comment by pbranly** [comment]
Hi
It works
Thanks
just one remark: on my list, it found many information but only for 3
photos for the column "department"
Any idea ?
Phil

Le mer. 4 janv. 2023 à 17:17, Viktor Nemeth ***@***.***> a
écrit :

**Comment by nemethviktor** [comment]
Can you copy the pictures to your dropbox pls - I basically need at least one that works ok and at least one that doesn't.
I'm assuming the gpx file is the one you already have on Dropbox (?)

**Comment by nemethviktor** [comment]
Btw I tried the one you sent yesterday and with a -2 hrs adjustment in worked as such:
![image](https://user-images.githubusercontent.com/58767235/210730109-33fbed31-6a40-4d85-a2d7-8dd7931d7315.png)

(hope you don't mind me pasting those details, I cropped it so nothing of particularly identifiable is on it.)

**Comment by pbranly** [comment]
fixed with version  0.7.8405 [20230105:0919]
Thanks
Phil
