### ISSUE TITLE
[Bug] EditForm: DateTime greyed out after changing between pictures with and without take datetime

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#48]
**Describe the bug**

I cannot change the Taken Date anymore, as the dt picker and the insert button are grayed out:
![grafik](https://user-images.githubusercontent.com/1786902/211140907-ebb6c301-a8b0-4a69-bb28-592576253b55.png)

**To Reproduce**
1. Select multiple images w/o taken date: ![grafik](https://user-images.githubusercontent.com/1786902/211140862-52e257c6-40df-4bdb-b0cb-882399f44629.png)
2. Start editing these (edit form opens)
3. For the first image, insert a new taken date
4. switch to a different picture without taken date
5. switch back to the picture for which the taken date was just inserted
6. After that, I cannot edit or insert the taken date in any picture currently in the edit form

**Expected behavior**
The dialog should be presented as before switching to the other picture.

**Additional info**
The same behavour happens when...
1. Select images with and without a taken date
2. Start editing these (for me, a picture with taken date is selected automatically): 
![grafik](https://user-images.githubusercontent.com/1786902/211141104-0854660d-9203-4c41-b23d-6e870323bb4d.png)
3. switch to a picture without taken date: 
![grafik](https://user-images.githubusercontent.com/1786902/211141123-e8d07b63-b833-4b50-85e3-904d98799f4f.png)
4. After that, I cannot edit or insert the taken date in any picture currently in the edit form

**Comment by Urmel** [comment]
Oh - I'm using Dev branch with commit SHA ae13df316ce194c360b04d154b224ab7f3203f48 as of 4.1.23

**Comment by nemethviktor** [comment]
Noted, thanks, will have a look next week. The one you're using is similar to the newest (as in that this area hasn't changed in the one in yesterday's Dev release)

**Comment by nemethviktor** [comment]
Just (now) posted a new one on google drive, can you give it a whirl please and see if it works ok?
