### ISSUE TITLE
Option to ignore reverse geocoding

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#53]
**Is your feature request related to a problem? Please describe.**
I want to define the location names myself, because I want to have the places in the local language, not e.g. in English. I haven't defined the Geonames account, and when I add coordinates from the GPX file, I get two error messages for each file that I have to acknowledge.

**Describe the solution you'd like**
If the Geonames account is empty, skip the reverse geocoding.

**Describe alternatives you've considered**
A maybe more clear alternative would be to have a tick box for reverse geocoding (do you want ...), and if it is ticked, then the username and password field would be active.

**Comment by nemethviktor** [comment]
Just to double check, this (`ignore` button [or similar]) would be specific to the GPX-parsing, right?

**Comment by lintujuh** [comment]
Yes. When I import a GPX file, I want only the "raw" information from the file mapped to the images.

**Comment by nemethviktor** [comment]
Noted, I'll add that in

**Comment by Clariden** [comment]
> I want to have the places in the local language, not e.g. in English

When doing reverse geocoding, It may also be a good idea to use the `lang` parameter of GeoNames--either with the OS language or with a language set by the user.

**Comment by nemethviktor** [comment]
> > I want to have the places in the local language, not e.g. in English
> 
> @nemethviktor When doing reverse geocoding, It may also be a good idea to use the `lang` parameter of GeoNames--either with the OS language or with a language set by the user.

Probably "set by the user" would be better. E.g. in @lintujuh  's case he's set to English-Finland, so he'd still see stuff in English if that was pulled from the environment. 
I'll add a dropdown for that.

**Comment by Clariden** [comment]
> Probably "set by the user" would be better.

Or use the OS language by default and let the user choose if he want to override it.

**Comment by lintujuh** [comment]
Actually I like to see the place names in the local language, E.g. Roma (it), instead of Rome (en) or Rooma (fi). I don't know how Geonames works, is it possible to say to use the local name?

**Comment by nemethviktor** [comment]
> Actually I like to see the place names in the local language, E.g. Roma (it), instead of Rome (en) or Rooma (fi). I don't know how Geonames works, is it possible to say to use the local name?

Possibly but that's up to the API database. I do have a working test version (not uploaded anywhere just yet) that uses a user-defined language (however there is no such thing as "local language" but you can predefine in the Settings say "Italian", which will be in affect until changed otherwise) -- however if the API database for Italian returns Rome rather than Roma there's little I can do (but you can set custom rules if you'd like).

**Comment by Clariden** [comment]
@nemethviktor 
> however there is no such thing as "local language"

There is. Use `lang=local` in the Geonames query.

**Comment by nemethviktor** [comment]
Ahh. Didn't know that! 
I'll add that in. Thanks ;)

**Comment by nemethviktor** [comment]
Ok can everyone interested try the [usual link](https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link)

![image](https://user-images.githubusercontent.com/58767235/212951557-eb4ba6b6-e1d3-4baa-965f-ca65a5aae946.png)

Revamped the Settings Form a bit - see block in the middle.

Also as per original request added a checkbox to the Import Form to ignore the API.
