### ISSUE TITLE
Track Sync: Remember Shift Track Time

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#59]
**Is your feature request related to a problem? Please describe.**
When I sync my files, I discover that I missed to adjust the clock in my camera. After I did the syncing, I forget to do so and run into the same situation next time.

**Describe the solution you'd like**
Instead of every time trying to figure out the exact shift, I would like to have as a preset the last used Shift Track Time:
![grafik](https://user-images.githubusercontent.com/1786902/213820288-e3578aa8-2f10-438a-838a-c4980a5a477a.png)

**Comment by nemethviktor** [comment]
Will do next week (most likely)

**Comment by Urmel** [comment]
Thanks for implementing this!
I guess we can then just close it...
