### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by TWCunningham** [nemethviktor/GeoTagNinja#6]
I off-handedly attempted a build with Visual Studio 2019 and got all kinds of arbitrary compiler errors.  Don't know what kind of .NET framework I should be using or other configuration/build parameters.  Anything special about building this beast?

**Comment by nemethviktor** [comment]
Hmm, good question. I haven't tried cloning it from git, might try one of these days. I was using VS Community 2022 but I don't think there's a lot of difference between '19 and '22. If you have all the nuGets pulled I think you need to set the output to be x86 (rather than x64, which has to do with SQLite).  -- Am thinking maybe some of the paths are hardcoded? (not on purpose, but I don't know how VS does some of the file relations.). If you can't get it to work I'll have a look at some point this week or next.

**Comment by nemethviktor** [comment]
On further examination:
I've cloned the git on one of my VMs where I'm not logged in (so I'm much like any other "random" user)
- There are 2 parts to the project. One is the "main" the other is the installer. You'll generally have problems w/ the installer bcs it hasn't been pushed to git so it's going to be missing that half. 
- For the "main" project you should be okay without anything separate. It has worked ok for me. Just build and F5/run.

**Comment by TWCunningham** [comment]
I installed Visual Studio 2022, but I still get errors in helper.cs (I only build GeoTagNinja not the Setup).  It complains starting with "Create TABLE settings"; clearly something isn't getting included somewhere.  I'm assuming this has something to do with SQLite, but System.Data.SQLite is included at the top.  Is a puzzlement.

**Comment by nemethviktor** [comment]
Did you get the nuGet packages? (in Solution Explorer, right click on GeoTagNinja, there should be something there about nuGets)

**Comment by TWCunningham** [comment]
I selected "Manage NuGet Packages..." and performed all updates but I still get the syntax error on CREATE TABLE settings in helper.cs.  Something's still missing....

**Comment by nemethviktor** [comment]
I've been poking around but not had any luck. Did you download the source code as zip and opened that or cloned the git in VS? If I download the source code it doesn't even build for some reason (no errors given just "skipped") but if I clone the git on a super-new-VM it works out of the box, builds and runs.

**Comment by TWCunningham** [comment]
Well dang, that was it!  As you say, cloned it and it built no problem.  Guess I'm just too old school, I've always downloaded from GitHub with no issues.  Anyway, thanks for the heads-up!

**Comment by nemethviktor** [comment]
Great to hear :)
