### ISSUE TITLE
Paste Meta Data: Remember Last Selection + General All/None Buttons

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#60]
**Is your feature request related to a problem? Please describe.**
I often use copy / past to set the time zome of images. When I past multiple times, I always have to set the check mark at time zone again.

**Describe the solution you'd like**
- The paste meta data dialog remembers which meta data I pasted last time and checks these fields again
- In order to easily change things, there should also be an all and none button that un/sets all check marks

**Comment by nemethviktor** [comment]
![image](https://user-images.githubusercontent.com/58767235/213859910-741aac2b-a201-4038-8c9b-5c299e59d49d.png)

There is an all/none button for each groupbox....you'd like a "total" all/none?

**Comment by Urmel** [comment]
> There is an all/none button for each groupbox....you'd like a "total" all/none?

Yesss - as I'm a lazy person, I just want to press one button ;)

**Comment by nemethviktor** [comment]
Done :)

**Comment by Urmel** [comment]
Cool :)
