### ISSUE TITLE
Go To Favorite Button

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#65]
**Is your feature request related to a problem? Please describe.**
Sometimes, I want to go some place near a favorite, which at the moment means manually (or using the address search) going there.

**Describe the solution you'd like**
I would like to have a button "go to favorite" so that the map is centered on the selected favorite.

**Comment by nemethviktor** [comment]
Tempted to just add the logic that if user picks a favourite from the drop-down the map should auto navigate there (?)

**Comment by Urmel** [comment]
Hmmm - sound reasonable. Only case that I can think of at the moment where it might hurt is if you accidently click on the favorites combo box.... so I would say it sounds good.
:) We could also have navigation arrows (go to last position, etc.)

**Comment by nemethviktor** [comment]
Closing as this is in dev
