### ISSUE TITLE
Clicking on an image in German version results an Exception

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#66]
**Describe the bug**
Click the image...
![grafik](https://user-images.githubusercontent.com/1786902/216758896-03e568e1-0c48-457b-83f2-cca893b869fb.png)

results in exception:
![grafik](https://user-images.githubusercontent.com/1786902/216758916-03eccfab-d43c-41e1-9257-c0e478f27ce4.png)

Used latest dev version:
* SHA-1: 60084bc2c9b794f4e132cc6ab4a928ef1e9e4ac3 "_Added logic to replace hard-coded City-definition logic with user choices + random bugfixes_"

**Solution Proposal**
Use number values from directory element instead.

**Comment by nemethviktor** [comment]
I'll have a look -- using the DE prob wouldn't work because remember that if there had been a change then data sits in DT3.
I think this was triggered by me changing textboxes to NUDs (and meanwhile doing away with some of the parse-logic) and not testing it on non-English versions. My bad. Will have a look next week.

**Comment by Urmel** [comment]
> I'll have a look -- using the DE prob wouldn't work because remember that if there had been a change then data sits in DT3. I think this was triggered by me changing textboxes to NUDs (and meanwhile doing away with some of the parse-logic) and not testing it on non-English versions. My bad. Will have a look next week.

Ok - so there might also be the solution to additionally write updates to the DEs...?

To my knowledge, we have the following update scenarios:
* Edit form
* Remove Location Data (toolbar)
* Paste GeoData
* Track Sync

**Comment by nemethviktor** [comment]
I need to go now but copied an updated version to the usual temp folder. It should largely work but the Edit Form NUDs still misbehave if you change them. I'll do that later, this is just to make it workable should you actually want to use it over the weekend.

It's the usual f...ing Culture setting. Dots and commas being f...ks - bane of my life. :D

**Comment by Urmel** [comment]
Hi @nemethviktor,
**thanks a lot for that** - really appreciate it (whereby it wasn't my intention to get a fix asap...)!

Yeah - cultural difference cause issues all over the place ;) How about my suggestion above: proceed in removing this culture stuff alltogether...?

**Comment by nemethviktor** [comment]
Hey, I'm still out and about so I'll be brief - I think for the time being I'll fix the culture issue just because it's easier and most of all faster to do/code. I'm with you on the DE conversion but that will take longer as per various conversations we've had.
:)

**Comment by nemethviktor** [comment]
Closing as this is in dev now
