### ISSUE TITLE
Favorites in German version are all at 180 / 180 coordinates

### ISSUE THREAD

**Issue by Urmel** [nemethviktor/GeoTagNinja#68]
**Describe the bug**
When I select a favorite, the long/lat below the map shows 180/180 and there it also jumps to:
![grafik](https://user-images.githubusercontent.com/1786902/216759784-ac97c150-60ba-4237-9319-e624088e59bb.png)

Used latest dev version:
* SHA-1: https://github.com/nemethviktor/GeoTagNinja/commit/60084bc2c9b794f4e132cc6ab4a928ef1e9e4ac3 "Added logic to replace hard-coded City-definition logic with user choices + random bugfixes"
* Plus PR https://github.com/Urmel/GeoTagNinja/commit/1c9904755cc048c147e82d3ae53ba38a2c5ec66d

**Comment by nemethviktor** [comment]
This is likely to be the same issue as 66 - when I replaced textboxes w/ NUDs I changed around how data is parsed and didn't test on non-UK. Will look next week, sorry :/

**Comment by nemethviktor** [comment]
Closing as this is in dev now
