### ISSUE TITLE
Manage Favorites missing option to change country

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#76]
**Describe the bug**
Manage Favorites dialog has an option to change Lat, Long, Alt, State, City and Sublocation, but not Country.

**To Reproduce**
Open the Manage Favorites dialog.

**Expected behavior**
There should also be a possibility to update the Country.

**Screenshots**
![image](https://user-images.githubusercontent.com/5797282/224549162-e2366fad-f481-4462-b644-7f89a44bf545.png)

**Comment by nemethviktor** [comment]
Hi, 

That's a feature - the logic is that in the big scheme of things the country to which a coordinate pair belongs don't change and since they are a set of hardcoded values that the user can't change (ie not a text field) that wasn't added in.

**Comment by lintujuh** [comment]
This is maybe just my workflow, but I want to have the coordinates in the RAW file, but the place names in xmp.

What happened was that I messed with one of my favorites, and I had to copy the coordinates from an old image where I had already added the place (in the xmp). I could clear all the other fields except the country.

**Comment by nemethviktor** [comment]
Can you have a look at the installer in the usual development google drive temp folder pls, i just patched this in.

**Comment by lintujuh** [comment]
Works fine. Thank you!
