### ISSUE TITLE
Copy-Paste tags copies also times by default

### ISSUE THREAD

**Issue by lintujuh** [nemethviktor/GeoTagNinja#77]
**Is your feature request related to a problem? Please describe.**
I don't want to change the timestamps of my images, but copy-paste tags has it enabled by default. I would prefer to have it turned on optionally.

![image](https://user-images.githubusercontent.com/5797282/224820087-1184a79c-4f33-41c8-9693-a84b53922ed1.png)

**Additional context**
I think this is introduced in the latest development version. I don't think this existed earlier.

**Comment by nemethviktor** [comment]
Ok try the usual googledrive location please, just pushed a new build there.

**Comment by lintujuh** [comment]
Thank you! Works fine.
