### ISSUE TITLE
Remember Altitude/Toponomy answer

### ISSUE THREAD

**Issue by PeterBDa** [nemethviktor/GeoTagNinja#8]
Perhaps another 'nice to have': 'a 'don't ask me again' checkbox in the Altitude/Toponomy popup. The answer for the first photo will often also be the answer for all the subsequent ones.

**Comment by nemethviktor** [comment]
I'll add it in :)

**Comment by PeterBDa** [comment]
Please don't rush on my account!

**Comment by PeterBDa** [comment]
Yes! This is exactly how I imagined it - really useful!

**Comment by nemethviktor** [comment]
Awesome ;) - okies, will push the version then shortly.
