### ISSUE TITLE
Imperial measurement option?

### ISSUE THREAD

**Issue by TWCunningham** [nemethviktor/GeoTagNinja#82]
**Is your feature request related to a problem? Please describe.**
Is there a way to get Imperial measurements in GeoTagNinja? (Sorry for being so old-fashioned :-/ )

**Describe the solution you'd like**
An option for specifying metric or Imperial measurements

**Describe alternatives you've considered**
Most of my photo metadata is written with Imperial measurements. I suppose I would have to convert manually. :-(

**Comment by nemethviktor** [comment]
I'll have a look - is it just the settings (like radius etc) + altitude you'd like or anything else in particular?

**Comment by TWCunningham** [comment]
Yes, I think it was altitude where I noticed it. Just anywhere there is a metric measurement provide an option for doing Imperial as well. Thanks!

**Comment by nemethviktor** [comment]
Okies, I'll have a look but FYI the values will remain metric per se, but I'll code it to show imperial (GPSAltitude, as well as the API we're using are hard-coded as metric, so the data written/sent won't change.)

**Comment by nemethviktor** [comment]
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/c9a08805-1784-41c0-a00d-a690a96babdf)

Can you have a look at https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=drive_link
Also on this occasion do make backups of your files pls just to make sure we're all okay with what the code does before it might upset something ;)

**Comment by TWCunningham** [comment]
Hey, that's great, thanks so much! I tried selecting several files and then chose Edit Files and GTN crashed! Shall I enter a new bug report?

**Comment by nemethviktor** [comment]
No, I'll have a look, I didn't test on multiple files. Will do now.

**Comment by nemethviktor** [comment]
Nvm, found it. Will look into that.

**Comment by nemethviktor** [comment]
Right, try the same link now - it has the same build number as earlier today so you might need to uninstall the old one explicitly if Windows Installer gets precious
Basically the issue you found wasn't related to the Imperial things. For some reason it was some legacy code being left in that misbehaved.

**Comment by TWCunningham** [comment]
Works fine now :-). Your time shift will come in handy for bulk adjustments, as I often forget to change my camera date/time. I didn't realize you could keep exiftool open and communicate through stdin/stdout, pretty slick! I'm assuming that's all Phil does in his ExifTool C++ interface, although it appears he includes a watchdog process in case things go wonky.

**Comment by nemethviktor** [comment]
Yayy, glad it works! :)
