### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by pbranly** [nemethviktor/GeoTagNinja#9]
Hi 
Thanks for your very promising application
Would you need any help for French translation ?
If yes provide me the source and procedure
Regards
Phil

**Comment by nemethviktor** [comment]
Yes, than you ;)
I'll send some instructions on how to do it early next week, should be relatively simple -- thanks again ;)

**Comment by nemethviktor** [comment]
Right - In the ExtraFiles folder there's an xlsx file called "english.xlsx". Copy that to "french.xlsx" and edit all the values in all the sheets (it's quite obvious which values need editing). 
That's kind of it. Just attach the completed file here and I'll do the rest. I will need to do some testing on my side because while "it should work" I haven't actually tried the languages thing so far.

**Comment by pbranly** [comment]
[french.xlsx](https://github.com/nemethviktor/GeoTagNinja/files/9860937/french.xlsx)

In the first line : 
Files ----> Fichiers
Settings -----> Paramètres
Help ----> Aide

Under Files:
Sauver tout
Editer les fichiers
Copier toutes les Geodatas
Coller toutes les Geodatas

Under Settings:
Paramètres

Under:
Application   Option de fichier

Under application:
Repertoire par défaut

etc ...... not sure you have a file for that

Phil

**Comment by nemethviktor** [comment]
hi Phil, 

Thanks for that - I'm afraid there's a bit more to do tho ;) -- there are a fair few sheets in the workbook, all of them need doing :/ :) [although the messageboxes, which is the one you did are the bulk of the task]
Btw specific to the Label sheet - I don't have a "policy" of whether the GPS tags (such as "Longitude Ref") should or should not be translated. I'm happy to go along with what had been in Geosetter. 
Thanks again :)

**Comment by pbranly** [comment]
This is not critical I think that remaining menus are technical and so somehow self understandable for the majority of us in English.
Phil

**Comment by nemethviktor** [comment]
Okay have a look at this one pls -> https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=sharing 
It has the French translation (amended a little, added in some google-translated bits here and there.)
Will post it in the other thread too as there's some further changes in this.

**Comment by pbranly** [comment]
it does not work: no language choice in the settings; it just shows English; in addition the Map is not present anymore
I came back to the yesterday version and map is back

**Comment by nemethviktor** [comment]
Ahh. Stupid installer. So French works for me because i don't "install" the program but just run it locally but the installer is stupid enough not to realise there is a new file in the Languages folder. 
I'll have a look at the map issue separately and get back to you.

**Comment by nemethviktor** [comment]
Right, try again please now, same link as above.

**Comment by nemethviktor** [comment]
Closing as done - feel free to comment further though if needed.
