### ISSUE TITLE
Current coordinate

### ISSUE THREAD

**Issue by grasdk** [nemethviktor/GeoTagNinja#91]
**Is your feature request related to a problem? Please describe.**
When I have 10 pictures taken in the same location and the first 5 have bad coordinates (phone gps not "zeroed in"), I want to select photo number 6, 7, 8, 9 or 10 (any) and set Current Coordinate from this picture. When re-selecting picture 1-5 I want to keep current coordinate from before, so I can assign it. Right now, the current coordinates follows the selected photo.

**Describe the solution you'd like**
Current coordinate is set independently from selected photo.
Corrent coordinate can be set from selected photo with a button, context menu, shortcut key or all of these
Current coordinate is marked on the map with different color marker

**Describe alternatives you've considered**
I have used GeoSetter for many years (it still works with openstreemaps). It has the above feature.

**Comment by nemethviktor** [comment]
Hi, 

Actually there are a few ways you can already do this. 

1. probably the easiest is that the location of the last-selected file counts as "current" in terms of map and "set location". So if you have a bunch of bad (coord) files, select them, and at last select the good file. You can use Ctrl to do the selection like in Windows Explorer if you want something like 1.jpg, 2.jpg, 4.jpg, 3.jpg sort of order (in this case 3.jpg being the good one). Then once that's done you can just set coordinate from map and it will apply to your selections.
2. you can alternatively select your good file, then Ctrl + Shift + C, then select your bad files, Ctrl + Shift + V and paste the relevant data.
3. alternatively again you can select all the files, Ctrl + Enter to Edit and there's a button to set active values across the files there.
