### ISSUE TITLE
Open Coordinates in API fails - dots missing

### ISSUE THREAD

**Issue by grasdk** [nemethviktor/GeoTagNinja#93]
**Describe the bug**
When right clicking "Open Coordinates in API", a browser tab opens, but the geonames api reports "Invalid lat/lng"

`{"status": {
  "message": "invalid lat/lng",
  "value": 14
}}`

The bug appears to be that the coordinates are missing the point marks (dots).
I use Firefox under Windows 10

**To Reproduce**

1. Right click a picture in file list, select option "Open Coordinates in API". Picture coordinates are 57.746284N, 10651275E
2. Brower tab opens with URL: http://api.geonames.org/findNearbyPlaceNameJSON?formatted=true&lat=57746284&lng=10651275&lang=local&style=FULL&radius=10&maxRows=1&username=MYUSERNAME&password=any

**Expected behavior**
Browser tab should up with URL containing dots
http://api.geonames.org/findNearbyPlaceNameJSON?formatted=true&lat=57.746284&lng=10.651275&lang=local&style=FULL&radius=10&maxRows=1&username=MYUSERNAME&password=any

**Screenshots**
![GeoTagNinjaAPIBug1](https://github.com/nemethviktor/GeoTagNinja/assets/115414609/d932eed4-44ce-4a8b-978d-1c6efdec8bb4)
![GeoTagNinjaAPIBug2](https://github.com/nemethviktor/GeoTagNinja/assets/115414609/cbcb8c0e-c3fc-482f-9ae7-ad9046302b9e)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Language/Culture: da-DK

**Comment by nemethviktor** [comment]
Ok see if this works -> https://drive.google.com/open?id=16laoPJcsJJz6mdkcjWvoQu6wWXiILbQy&usp=drive_fs [this is the same link as for 94 so you don't need to test them separately, I just patched both]

**Comment by grasdk** [comment]
Works! :)
