### ISSUE TITLE
Add toponomymName and/or name as option for Custom City Assignment Logic

### ISSUE THREAD

**Issue by grasdk** [nemethviktor/GeoTagNinja#94]
**Is your feature request related to a problem? Please describe.**
When using geonames to lookup names, I want to be able to select toponomymName or name as City name. Reason is that AdminName2 is "Municipality" for the Danish geonames data in geonames api. Municipalities are not cities. :)

**Describe the solution you'd like**
Ability to select topononymName and/or name in the dropdown-box under Custom City Assignment Logic

**Describe alternatives you've considered**
I considered Custom Rules, but I wasn't able to select Denmark in that tab, and I got some error messages when clicking _Include "Predetermined" countries_ (a bug to report, I guess). Regardless, I think it would be cleaner to add options to Custom City Assignment Logic

![GeoTagNinjaAPIFeatureCityLogic](https://github.com/nemethviktor/GeoTagNinja/assets/115414609/dfadb266-b0d3-48eb-a7bc-0b91f1ac9c52)

**Comment by nemethviktor** [comment]
Ok see if this works -> https://drive.google.com/open?id=16laoPJcsJJz6mdkcjWvoQu6wWXiILbQy&usp=drive_fs
I've added in toponomymName and did a rather very superficial test and I think it works. 
Also patched the bug re Predefined Countries while at it, thanks for pointing it out.

**Comment by grasdk** [comment]
It works. Sublocation is cleared: I don't know if this is intentional. Maybe it is, because topononymName used to be used for Sublocation?

Oh and we made the same spelling mistake: topono**m**ymName (in the settings dropdown).

**Comment by nemethviktor** [comment]
Heh, lol I do dislike that word. Difficult not to misspell. I also have some typos in the readme unrelated, which is great as I'm a bit of a grammar-nazi. Alas should drink more coffee and less wine.

Yes, sub-location blank is on purpose but it's also related to the original coding of the logic (where your request hadn't been part of it.)
Not sure if you read C# but Denmark is part of `defaultCityNameIsAdminName2Arr` and in Helpers\HelperExifReadExifData.cs around lines 138:
```
if (HelperVariables.LstCityNameIsAdminName1.Contains(item: CountryCode) ||
    HelperVariables.LstCityNameIsAdminName2.Contains(item: CountryCode) ||
    HelperVariables.LstCityNameIsAdminName3.Contains(item: CountryCode) ||
    HelperVariables.LstCityNameIsAdminName4.Contains(item: CountryCode)
   )
{
    isPredeterminedCountry = true;

    Sub_location = ToponymNameInSQL;

    if (HelperVariables.LstCityNameIsAdminName1.Contains(item: CountryCode))
    {
        City = AdminName1InSQL;
        State = "";
    }
    else if (HelperVariables.LstCityNameIsAdminName2.Contains(item: CountryCode))
    {
        City = AdminName2InSQL;
    }
    else if (HelperVariables.LstCityNameIsAdminName3.Contains(item: CountryCode))
    {
        City = AdminName3InSQL;
    }
    else if (HelperVariables.LstCityNameIsAdminName4.Contains(item: CountryCode))
    {
        City = AdminName4InSQL;
    }

    if (City == Sub_location)
    {
        **Sub_location = "";**
    }

    if (!HelperVariables.LstCityNameIsAdminName1.Contains(item: CountryCode))
    {
        State = AdminName1InSQL;
    }
}
```
Logically so that city and sublocation don't duplicate.
