### ISSUE TITLE
Cannot save coordinates when path contains ÆØÅ

### ISSUE THREAD

**Issue by RevBlood** [nemethviktor/GeoTagNinja#95]
**Describe the bug**
Cannot save updated coordinates when file path contains ÆØÅ characters

**To Reproduce**
1. Put a picture in a path containing æ ø or å
2. Change the coordinates of the picture using GeoTagNinja
3. Attempt to save changes, e.g. by saving upon navigating to a different folder.
4. You should now have an error saying "File Not Found"

**Expected behavior**
File saved successfully

**Screenshots**
![image](https://github.com/nemethviktor/GeoTagNinja/assets/3540099/bba5e625-0b38-4343-9b93-a581b70a7ca1)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Language/Culture da-DK
 - Full Path of Picture: C:/Users/treel/OneDrive/Kamerarulle/2023/06-Sorted/[06-27] Anna 31 År/20230627_111711.heic

**Additional context**
It's possible to rename the affected folder to avoid this issue, but unsaved changes inside of folder will always be lost, and you must start over.

**Comment by nemethviktor** [comment]
Hi, I'll have a look but I think it's going to be the one in the
documentation (ie file path limit is a hard 260 chars for exiftool and
special/certain unicode characters don't work well with ET as they take up
more than 1 byte)
